on:
    workflow_dispatch:
    pull_request:
        types: [opened, edited, synchronize]

jobs:
    lwc-tests:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout source code"
              uses: actions/checkout@v3

            - name: "Install Volta"
              uses: volta-cli/action@v4

            - name: "Restore node_modules cache"
              id: cache-npm
              uses: actions/cache@v3
              with:
                path: node_modules
                key: npm-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                    npm-${{ env.cache-name }}-
                    npm-

            - name: "Install npm dependencies"
              if: steps.cache-npm.outputs.cache-hit != 'true'
              run: npm ci
            
            - name: "Run eslint"
              run: npm run lint

            - name: "Run LWC tests"
              run: npm run test:unit:coverage
    
    
    